# Backend Configuração
backend:
  image:
    repository: leonamvasquez/backend
    tag: latest
  replicaCount: 2
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
  env:
    FLASK_APP: "run.py"
    FLASK_DB_TYPE: "postgres"
    FLASK_DB_USER: "myuser"
    FLASK_DB_PASSWORD: "mypassword"
    FLASK_DB_NAME: "mydatabase"
    FLASK_DB_HOST: "postgres"
    FLASK_DB_PORT: "5432"

# Frontend Configuração
frontend:
  image:
    repository: leonamvasquez/frontend
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: "300m"
      memory: "128Mi"
    requests:
      cpu: "150m"
      memory: "64Mi"
  env:
    REACT_APP_BACKEND_URL: "http://backend:5000"

# PostgreSQL Configuração
postgres:
  image:
    repository: postgres
    tag: latest
  replicaCount: 1
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  storage:
    size: 1Gi
  env:
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "mypassword"
    POSTGRES_DB: "mydatabase"

# HPA Configuração para o Backend
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
