apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: leonamvasquez/backend
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "run.py"
        - name: FLASK_DB_TYPE
          value: "postgres"
        - name: FLASK_DB_USER
          value: "myuser"
        - name: FLASK_DB_PASSWORD
          value: "mypassword"
        - name: FLASK_DB_NAME
          value: "mydatabase"
        - name: FLASK_DB_HOST
          value: "postgres"
        - name: FLASK_DB_PORT
          value: "5432"
